### ISSUE TITLE
Change to run under low-priv account

### ISSUE THREAD

**Issue by andreasjunestam** [iSECPartners/yontma#1]
Currently runs under system, should be changed to run under an account with less privs. Account needs shutdown priv though, so user might be better than localservice.

**Comment by andreasjunestam** [comment]
So, localservice does not have the permission to shut down the machine. Best way to solve this (it seems like), would be to add a yontma user.
Install:
1. Create yontma user with random password
2. Create service under yontma user
3. Start service

Uninstall:
1. Stop service
2. Remove service
3. Delete yontma user

Is it worth doing this? I think it is to get it running under a less priv account.

**Comment by andreasjunestam** [comment]
Closed.

**Comment by mlynch-isec** [comment]
Reopening. This isn't actually fixed yet. See changelist descriptions for details.
