### ISSUE TITLE
Handle never logged in case

### ISSUE THREAD

**Issue by mlynch-isec** [iSECPartners/yontma#10]
yontma should handle the case where the machine is booted up, but the user has not yet logged in. It might already handle this, but we need to verify.

**Comment by andreasjunestam** [comment]
This can probably be solved by firing off a thread when the service starts. The thread sleeps for X seconds and then checks if the machine is locked. Question is how to query the lockstate. There is not straightforward function and as a service we don't have UI interaction so I'm not sure we can query for the current desktop.

**Comment by andreasjunestam** [comment]
And to finish that comment.. :) In any case, if the machine is found to be locked, set the lock state accordingly.

**Comment by andreasjunestam** [comment]
Solved. Will be part of large checking at some point.
