### ISSUE TITLE
Verify it works when device is asleep

### ISSUE THREAD

**Issue by mlynch-isec** [iSECPartners/yontma#15]
See if we can hibernate if the service is running, device is put to sleep, then unplugged.

**Comment by mlynch-isec** [comment]
We can possibly just force hibernation if the user tries to sleep when YoNTMA is running.

**Comment by andreasjunestam** [comment]
I think that would be against the "spirit" of Jesse's use scenario. He mentioned going to a meeting, sleeping the machine without locking, starting ii back up and hooking it up, then going for lunch. So I think we need to handle the sleep case as is.

**Comment by mlynch-isec** [comment]
To clarify, the scenario is:
1. User is logged into their laptop.
2. User puts laptop into suspend (not hibernate) by closing the lid (without explicitly locking machine)
3. User wakes laptop up

Expected behavior:
Yontma does not hibernate the machine upon waking, regardless of whether AC power or wired Ethernet status changed
